Temporary edits pending discussion
SolutionGuidance/psm-dashboard pull request #1
Opened 2018-05-04 16:56 UTC by cecilia-donnelly

Show less information on burndown tooltips.  Move pie chart next to burn
down chart.

What do you think of these changes, @PaulMorris?

2018-05-04 21:10 UTC, PaulMorris requested changes
@cecilia-donnelly These changes look good to me!  The page layout may evolve as we build this out (like we may want to use flexbox instead of floats) but this looks good now.  Just one suggestion about the location of CSS styles.

2018-05-04 21:10 UTC, PaulMorris commented on burn-down.html
> +  <div style="float: right;" id="features-pie-chart"></div>
Probably worth putting these styles in the css file rather than as inline here.

2018-05-07 16:32 UTC, cecilia-donnelly commented
The other concern I had @PaulMorris was that I commented out a couple pieces of information [here](https://github.com/SolutionGuidance/psm-dashboard/pull/1/commits/ffcb091519e76178abba24366e82e1995bff4c46#diff-64ee083094e974278f0557180f333211L308) and should probably just remove them if you and @kfogel agree that we don't need them.

2018-05-10 16:51 UTC, cecilia-donnelly commented
Okay!  Updated this.  In keeping with the faster pace on this project I will just merge.

2018-05-10 18:36 UTC, merged